{% set name = "network-analyzer" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - libpcap
    - winpcap-sdk # [win]
    - fmt
    - cli11

  run:
    - libpcap
    - fmt
    - cli11

tests:
  - script:
    - network-analyzer

about:
  homepage: https://github.com/ahillodessa/conda_network_analyzer
  summary: Small network analyzer to show network packages
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - avetroumov