{% set name = "network-analyzer" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/ahillodessa/conda_network_analyzer/archive/refs/tags/v0.1.0.tar.gz"
  sha256: A77DA0ECB40526302B9FFACD9E0B8D83B9C2CD26EE8076B8E2AC87F8A1FF5BDC
build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

  host:
    - libpcap
    - fmt
    - cli11

  run:
    - libpcap
    - fmt

tests:
  - script:
    - network-analyzer -h

about:
  homepage: https://github.com/ahillodessa/conda_network_analyzer
  summary: Small network analyzer to show network packages
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - avetroumov