name: Build Conda Package

on:
  push:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build-conda:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux-64
          - os: windows-latest
            artifact_name: win-64
          - os: macos-latest
            artifact_name: osx-64

    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup rattler-build (Linux)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        shell: bash
        run: |
          curl -fsSL https://pixi.sh/install.sh | sh
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup rattler-build (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://pixi.sh/install.ps1 -OutFile install.ps1
          .\install.ps1
          echo "$env:USERPROFILE\.pixi\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Conda Package
        run: |
          # pixi exec rattler-build build --recipe conda-recipe/github_meta.yaml --output-dir dist
          pixi exec rattler-build build --recipe conda-recipe/github_meta.yaml -c conda-forge --no-build-id --channel conda-forge --output-dir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: network-analyzer-${{ matrix.os }}
          path: |
            dist/**/*.conda
            dist/**/*.tar.bz2
          if-no-files-found: error
          retention-days: 5